# tests/test_seo_booster.py
import unittest
from src.seo_protocol.seo_booster import SEOBooster
from unittest.mock import patch

class TestSEOBooster(unittest.TestCase):

    @patch('src.seo_protocol.seo_booster.ServiceAccountCredentials')
    @patch('src.seo_protocol.seo_booster.build')
    def test_get_improvement_suggestions(self, MockBuild, MockCredentials):
        """Test the improvement suggestions generated by the SEOBooster class."""
        booster = SEOBooster('https://github.com/username/repo', google_service_json=None)

        # Test suggestions generation
        suggestions = booster.get_improvement_suggestions(
            ['blockchain', 'solidity', 'ethereum'],
            ['defi', 'nft'],
            60,
        )

        # Validate the suggestions
        self.assertIn("X Post: 'Explore my blockchain project →", suggestions[0])
        self.assertIn("Blog/article idea: 'Deep dive into blockchain", suggestions[1])
        self.assertIn("Make README more discoverable", suggestions[2])
        self.assertIn("Consider adding trending keywords: defi, nft", suggestions[4])

    @patch('src.seo_protocol.seo_booster.ServiceAccountCredentials')
    @patch('src.seo_protocol.seo_booster.build')
    def test_try_submit_urls_to_google(self, MockBuild, MockCredentials):
        """Test submitting the repo URL to Google Indexing API (mocked)."""
        booster = SEOBooster('https://github.com/username/repo', google_service_json=None)

        # Mock Google Indexing API submission
        MockBuild.return_value.urlNotifications.return_value.publish.return_value.execute.return_value = {
            "urlNotificationMetadata": {"url": "https://github.com/username/repo"}
        }

        # Test URL submission to Google
        booster.try_submit_urls_to_google(urls=['https://github.com/username/repo'])

        # Ensure the Google API is called
        MockBuild.return_value.urlNotifications.return_value.publish.return_value.execute.assert_called_once()

if __name__ == '__main__':
    unittest.main()
